In [4]:
import numpy as np
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'

In [6]:
one_d = np.array([1, 3, 5, 9])

array([1, 3, 5, 9])

In [7]:
two_d = np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((3, 4, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [12]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.linspace(0, 1.1, 5)

array([0.   , 0.275, 0.55 , 0.825, 1.1  ])

In [17]:
# random.random, .normal, .randint
# randint does not include right endpoint

In [18]:
np.random.randint(0, 3, [5, 5])

array([[0, 1, 2, 2, 2],
       [1, 2, 1, 0, 1],
       [0, 0, 0, 1, 1],
       [1, 0, 0, 2, 0],
       [2, 1, 1, 2, 2]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])