In [1]:
import numpy as np

In [2]:
x = np.array([[1,0,3], [3,0,1], [5,0,9]])

In [3]:
x

array([[1, 0, 3],
       [3, 0, 1],
       [5, 0, 9]])

In [4]:
x.sum()

22

In [5]:
x.sum(axis=0)

array([ 9,  0, 13])

In [6]:
x.sum(axis=1)

array([ 4,  4, 14])

In [7]:
x3d = np.array([
    [
        [1,1],
        [2,2]
    ],
    
    [
        [3,2],
        [4,4],
    ]
])

In [8]:
x3d

array([[[1, 1],
        [2, 2]],

       [[3, 2],
        [4, 4]]])

In [10]:
x3d.sum(axis=0)

array([[4, 3],
       [6, 6]])

In [12]:
x3d.sum(axis=1)  # pretty confusing

array([[3, 3],
       [7, 6]])

In [21]:
np.all(x == 0, axis=1)

array([False, False, False])

In [22]:
np.all(x == 0, axis=0)  # collapse rows, look at columns

array([False,  True, False])

In [23]:
np.all(x == 0, axis=0)  # collapse rows, look at columns

array([False,  True, False])